### ISSUE TITLE
The flag file already exist, but isn't added. 

### ISSUE THREAD

**Issue by Kame03** [RMcGirr83/phpBB-3.1-nationalflags#27]
Referencing issue #26 the flags of these countries aren't available on the forums using this software, while when I forked this software and I tried to add the flags, I've already noticed that the flags exist in the flags folder:

![image](https://github.com/user-attachments/assets/045f3a61-b96b-433f-a69f-49093813334a)

So now I'm unsure what I'm supposed to do next, are they for some reason excluded from the code and why? and should I just add them in the m4_add_data.php

I've checked language file and few other php files in the forked project and they seem to have Serbia added, and those other missing countries, in composer.json it says the version is 2.3.5, while the latest release you have is 2.2.6 so it seems that this might be the cause of issues, as most forum owners just download the version from the release, which do not have these flags, but maybe I'm wrong, since this is only the language file and they probably need to be added in m4_add_data.php like you originally told me to. If that is the case I will make a pull request with the needed changes, just waiting on confirmation.

**Comment by rmcgirr83** [comment]
I think part of the problem is certain countries don't have specific ISO codes, for example Kosovo. They may have user-assigned codes https://en.wikipedia.org/wiki/XK_(user_assigned_code).  The language file doesn't have Kosovo nor Serbia in it nor either Yugoslavia. It does have Croatia, Slovenia, Boznia etc. Just missing a few. Slovenia should be available to select as a country. And NO you can not and should not simply add them to the m4_add_data.php file but should create a new migration file to add the ones that are missing as well as create language entries in the lang file. But then again using xk for Kosovo isn't necessarily correct as xk is a user defined ISO code  and any code beginning with x will never be accepted by the standard. As I said before, many flags have been auto added some may have been missed. If you make the migration file and use xk for Kosovo, I will deny the PR. You must follow ISO 3166 when adding the flags via a migration file. As far as I can tell Kosovo flag doesn't exist in the extension.

**Comment by Kame03** [comment]
Well, Serbia doesn't recognize Kosovo anyways, so I will not be touching that country, I simply want to add missing countries from Ex-Yugoslavia, also Yugoslavia dissolved so there's no need to add Yugoslavia as that country no longer exists.
As for your comment about needing to create a new migration file, I am sorry for asking  so many questions, but I want to do this properly, what is the naming standard I should use for the new migration file, and I already see Serbia as an entry in the language file, so do I need to add anything else there?

**Comment by rmcgirr83** [comment]
I added those as well as some others
https://github.com/rmcgirr83/nationalflags/commit/3bde9c4a24b740acdfda1d709fef3f08bb826c86
